//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ButtonConfiguration {
    
    private string toRecipientsField;
    
    private string ccRecipientsField;
    
    private string bccRecipientsField;
    
    private string onlineUrlField;

    private string guidanceUrlField;
    
    private string authorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string toRecipients {
        get {
            return this.toRecipientsField;
        }
        set {
            this.toRecipientsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ccRecipients {
        get {
            return this.ccRecipientsField;
        }
        set {
            this.ccRecipientsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string bccRecipients {
        get {
            return this.bccRecipientsField;
        }
        set {
            this.bccRecipientsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string onlineUrl {
        get {
            return this.onlineUrlField;
        }
        set {
            this.onlineUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string guidanceUrl
    {
        get {
            return this.guidanceUrlField;
        }
        set {
            this.guidanceUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string author {
        get {
            return this.authorField;
        }
        set {
            this.authorField = value;
        }
    }
}
