//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ButtonConfiguration {
    
    private string fromField;
    
    private string toRecipientsField;
    
    private string ccRecipientsField;
    
    private string bccRecipientsField;
    
    private string onlineUrlField;
    
    private string guidanceUrlField;
    
    private string authorField;
    
    private string currentVersionField;
    
    private string versionUrlField;
    
    private string sourceUrlField;
    
    private string standardSuffixField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string toRecipients {
        get {
            return this.toRecipientsField;
        }
        set {
            this.toRecipientsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ccRecipients {
        get {
            return this.ccRecipientsField;
        }
        set {
            this.ccRecipientsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string bccRecipients {
        get {
            return this.bccRecipientsField;
        }
        set {
            this.bccRecipientsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string onlineUrl {
        get {
            return this.onlineUrlField;
        }
        set {
            this.onlineUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string guidanceUrl {
        get {
            return this.guidanceUrlField;
        }
        set {
            this.guidanceUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string author {
        get {
            return this.authorField;
        }
        set {
            this.authorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string currentVersion {
        get {
            return this.currentVersionField;
        }
        set {
            this.currentVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string versionUrl {
        get {
            return this.versionUrlField;
        }
        set {
            this.versionUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sourceUrl {
        get {
            return this.sourceUrlField;
        }
        set {
            this.sourceUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string standardSuffix {
        get {
            return this.standardSuffixField;
        }
        set {
            this.standardSuffixField = value;
        }
    }
}
